In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [5]:
X_new = [[3,5,4,1],[5,3,4,2]]

In [9]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [10]:
logreg.fit(X_feature,Y_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
logreg.predict(X_new)

array([0, 2])

In [12]:
import pickle as pkl

In [14]:
persist_model = pkl.dumps(logreg)
persist_model

'ccopy_reg\n_reconstructor\np0\n(csklearn.linear_model.logistic\nLogisticRegression\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nS\'warm_start\'\np6\nI00\nsS\'C\'\np7\nF1.0\nsS\'n_jobs\'\np8\nNsS\'verbose\'\np9\nI0\nsS\'fit_intercept\'\np10\nI01\nsS\'solver\'\np11\nS\'warn\'\np12\nsS\'classes_\'\np13\ncnumpy.core.multiarray\n_reconstruct\np14\n(cnumpy\nndarray\np15\n(I0\ntp16\nS\'b\'\np17\ntp18\nRp19\n(I1\n(I3\ntp20\ncnumpy\ndtype\np21\n(S\'i8\'\np22\nI0\nI1\ntp23\nRp24\n(I3\nS\'<\'\np25\nNNNI-1\nI-1\nI0\ntp26\nbI00\nS\'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\'\np27\ntp28\nbsS\'n_iter_\'\np29\ng14\n(g15\n(I0\ntp30\ng17\ntp31\nRp32\n(I1\n(I1\ntp33\ng21\n(S\'i4\'\np34\nI0\nI1\ntp35\nRp36\n(I3\nS\'<\'\np37\nNNNI-1\nI-1\nI0\ntp38\nbI00\nS\'\\x07\\x00\\x00\\x00\'\np39\ntp40\nbsS\'intercept_scaling\'\np41\nI1\nsS\'penalty\'\np42\nS\'l2\'\np43\nsS\'multi_class\'\np44\ng12\nsS\'random_state\'\np45\nNsS\'_sklear

In [15]:
from sklearn.externals import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl']

In [17]:
new_logreg_estimator = joblib.load('regresfilename.pkl')
new_logreg_estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
new_logreg_estimator.predict(X_new)

array([0, 2])