In [1]:
import numpy as np

In [2]:
np.add(45,20)

65

In [3]:
np.subtract(45,23)

22

In [6]:
np_daily_wage = np.array([7,7,13,18,11])*15
np_daily_wage

array([105, 105, 195, 270, 165])

In [7]:
sum(np_daily_wage)

840

In [8]:
np_weekly_hrs = np.array([23,41,55,47,38])
np_weekly_hrs[np_weekly_hrs > 40]

array([41, 55, 47])

In [9]:
np_weekly_hrs[np_weekly_hrs != 40]

array([23, 41, 55, 47, 38])

In [12]:
np.logical_and(np_weekly_hrs<20,np_weekly_hrs<50)

array([False, False, False, False, False])

In [14]:
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])